#!/bin/sh
# Render prometheus.yml + file_sd target files from env, then exec Prometheus.
# Runs inside the busybox-based prom/prometheus image (sh + awk only).
#
# Target list format (comma separated, whitespace ignored):
#   NAME=HOST:PORT[;key=value...]
# keys: server, model, role (prefill|decode|unified), path (default /metrics)
# Defaults: server = VLLM_SERVER_NAMES[HOST] or HOST;
#           role   = prefill/decode if NAME contains it, else unified;
#           model  = NAME without -prefill/-decode/-nodeN suffixes.
set -eu

OUT=${PROM_GENERATED_DIR:-/prometheus/generated}
mkdir -p "$OUT/targets"
rm -f "$OUT"/targets/*.json

render() { # $1 = job/file name, $2 = target list
	printf '%s' "$2" | awk -v job="$1" -v servers="${VLLM_SERVER_NAMES:-}" '
	function trim(s) { gsub(/^[ \t\r\n]+|[ \t\r\n]+$/, "", s); return s }
	BEGIN {
		n = split(servers, sv, ",")
		for (i = 1; i <= n; i++) {
			s = trim(sv[i]); if (s == "") continue
			p = index(s, "="); if (p == 0) continue
			map[trim(substr(s, 1, p - 1))] = trim(substr(s, p + 1))
		}
		RS = "\001"
	}
	{
		n = split($0, items, ","); first = 1
		printf "["
		for (i = 1; i <= n; i++) {
			it = trim(items[i]); if (it == "") continue
			m = split(it, f, ";")
			p = index(f[1], "=")
			if (p == 0) { print "bad target entry (want NAME=HOST:PORT): " it > "/dev/stderr"; exit 2 }
			name = trim(substr(f[1], 1, p - 1)); addr = trim(substr(f[1], p + 1))
			host = addr; sub(/:[0-9]+$/, "", host)
			server = (host in map) ? map[host] : host
			role = "unified"
			if (name ~ /prefill/) role = "prefill"
			else if (name ~ /decode/) role = "decode"
			model = name
			sub(/-(prefill|decode)$/, "", model); sub(/-node[0-9]+$/, "", model)
			path = "/metrics"
			for (j = 2; j <= m; j++) {
				kv = trim(f[j]); q = index(kv, "="); if (q == 0) continue
				k = trim(substr(kv, 1, q - 1)); v = trim(substr(kv, q + 1))
				if (k == "server") server = v
				else if (k == "model") model = v
				else if (k == "role") role = v
				else if (k == "path") path = v
			}
			if (!first) printf ","
			first = 0
			printf "{\"targets\":[\"%s\"],\"labels\":{\"instance\":\"%s\",\"server\":\"%s\",\"model\":\"%s\",\"role\":\"%s\",\"address\":\"%s\",\"__metrics_path__\":\"%s\"}}", addr, name, server, model, role, addr, path
			printf "%s -> %s server=%s model=%s role=%s\n", job, addr, server, model, role > "/dev/stderr"
		}
		print "]"
	}' >"$OUT/targets/$1.json.tmp"
	mv "$OUT/targets/$1.json.tmp" "$OUT/targets/$1.json"
}

render vllm "${VLLM_METRICS_TARGETS:-}"
render vllm-router "${ROUTER_METRICS_TARGETS:-}"
render lmcache "${LMCACHE_METRICS_TARGETS:-}"
render gpu "${GPU_METRICS_TARGETS:-}"

# vLLM only guards /v1/* with --api-key, so /metrics is normally public.
# If a proxy in front requires a bearer token, mount it as a file.
TOKEN_FILE=${VLLM_METRICS_BEARER_TOKEN_FILE:-/run/secrets/vllm_metrics_token}
AUTH=""
if [ -s "$TOKEN_FILE" ]; then
	AUTH="    authorization:
      type: Bearer
      credentials_file: $TOKEN_FILE"
	echo "vllm job: bearer token file enabled" >&2
fi

job() { # name interval timeout [auth]
	cat <<EOF
  - job_name: $1
    scrape_interval: $2
    scrape_timeout: $3
    honor_labels: false
    file_sd_configs:
      - files: ['$OUT/targets/$1.json']
        refresh_interval: 30s
${4:-}
EOF
}

{
	cat <<EOF
# Generated by entrypoint.sh at container start. Do not edit.
global:
  scrape_interval: ${PROM_SCRAPE_INTERVAL:-10s}
  evaluation_interval: ${PROM_SCRAPE_INTERVAL:-10s}
  external_labels:
    monitor: ${PROM_MONITOR_NAME:-vllm-cmp170hx}
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:${PROM_PORT:-9090}']
        labels: {instance: prometheus, server: monitor}
EOF
	job vllm "${PROM_SCRAPE_INTERVAL:-10s}" 8s "$AUTH"
	job vllm-router "${PROM_SCRAPE_INTERVAL:-10s}" 8s
	job lmcache "${PROM_SCRAPE_INTERVAL:-10s}" 8s
	job gpu "${GPU_SCRAPE_INTERVAL:-30s}" 20s
} >"$OUT/prometheus.yml"

promtool check config "$OUT/prometheus.yml" >&2

exec /bin/prometheus \
	--config.file="$OUT/prometheus.yml" \
	--storage.tsdb.path=/prometheus \
	--storage.tsdb.retention.time="${PROM_RETENTION:-90d}" \
	--storage.tsdb.retention.size="${PROM_RETENTION_SIZE:-0B}" \
	--web.listen-address="${PROM_LISTEN:-127.0.0.1}:${PROM_PORT:-9090}" \
	--web.enable-lifecycle \
	"$@"
